<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Agents\Akka.Agents.csproj" />
  </ItemGroup>

</Project>
