<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Nuget package versions -->
    <AkkaHostingVersion>1.5.60</AkkaHostingVersion>
    <AkkaPersistenceSqlHostingVersion>1.5.60.1</AkkaPersistenceSqlHostingVersion>
    <AkkaRemindersVersion>0.4.0</AkkaRemindersVersion>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
    <PackageVersion Include="Akka.Hosting" Version="$(AkkaHostingVersion)" />
    <PackageVersion Include="Akka.Cluster.Sharding" Version="$(AkkaHostingVersion)" />
    <PackageVersion Include="Akka.Persistence" Version="$(AkkaHostingVersion)" />
    <PackageVersion Include="Akka.Persistence.Hosting" Version="$(AkkaHostingVersion)" />
    <PackageVersion Include="Akka.Persistence.Sql.Hosting" Version="$(AkkaPersistenceSqlHostingVersion)" />
    <PackageVersion Include="Aaron.Akka.Reminders" Version="$(AkkaRemindersVersion)" />
    <PackageVersion Include="Microsoft.Extensions.AI.Abstractions" Version="10.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageVersion Include="OllamaSharp" Version="5.4.16" />
    <PackageVersion Include="SlackNet" Version="0.17.9" />
    <PackageVersion Include="SlackNet.Extensions.DependencyInjection" Version="0.17.9" />
    <PackageVersion Include="Termina" Version="0.6.0" />
  </ItemGroup>
  <!-- Serialization -->
  <ItemGroup>
    <PackageVersion Include="protobuf-net" Version="3.2.30" />
  </ItemGroup>
  <!-- Test dependencies -->
  <ItemGroup>
    <PackageVersion Include="Akka.Hosting.TestKit" Version="$(AkkaHostingVersion)" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>
  <!-- Source generators -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
  </ItemGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.103" />
  </ItemGroup>
</Project>
