// -----------------------------------------------------------------------
// <copyright file="OnnxMemoryEmbedderTests.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using Xunit;

namespace Netclaw.Embeddings.Tests;

/// <summary>
/// Exercises <see cref="OnnxMemoryEmbedder"/> against the tiny fixture graph committed at
/// <c>Fixtures/tiny-embedder.onnx</c> / <c>Fixtures/tiny-vocab.txt</c> (generated by
/// <c>Fixtures/generate_fixture_model.py</c> — see that file's header comment for the graph
/// shape and why it mean-pools instead of doing a plain CLS passthrough). No network access;
/// this is the CI-safe substitute for the real ~110M/~335M-parameter allowlisted models.
/// </summary>
public sealed class OnnxMemoryEmbedderTests : IAsyncLifetime
{
    private const string ModelId = "tiny-fixture";
    private const int Dimensions = 8;

    private OnnxMemoryEmbedder _embedder = null!;

    public async ValueTask InitializeAsync()
    {
        var fixturesDir = Path.Combine(AppContext.BaseDirectory, "Fixtures");
        _embedder = await OnnxMemoryEmbedder.LoadAsync(
            modelPath: Path.Combine(fixturesDir, "tiny-embedder.onnx"),
            vocabPath: Path.Combine(fixturesDir, "tiny-vocab.txt"),
            modelId: ModelId,
            dimensions: Dimensions,
            maxConcurrency: 2);
    }

    public ValueTask DisposeAsync()
    {
        _embedder.Dispose();
        return ValueTask.CompletedTask;
    }

    [Fact]
    public void Loaded_embedder_reports_its_identity()
    {
        Assert.Equal(ModelId, _embedder.ModelId);
        Assert.Equal(Dimensions, _embedder.Dimensions);
        Assert.True(_embedder.IsAvailable);
    }

    [Fact]
    public async Task EmbedAsync_is_deterministic_for_the_same_text()
    {
        var v1 = await _embedder.EmbedAsync("cat sat on the mat", TestContext.Current.CancellationToken);
        var v2 = await _embedder.EmbedAsync("cat sat on the mat", TestContext.Current.CancellationToken);

        Assert.Equal(v1.ToArray(), v2.ToArray());
    }

    [Fact]
    public async Task EmbedAsync_produces_L2_normalized_vectors_of_the_declared_dimension()
    {
        var vector = await _embedder.EmbedAsync("hello world", TestContext.Current.CancellationToken);

        Assert.Equal(Dimensions, vector.Length);
        var normSquared = vector.ToArray().Sum(x => (double)x * x);
        Assert.True(Math.Abs(normSquared - 1.0) < 1e-4, $"expected unit-length vector, got ||v||^2={normSquared}");
    }

    [Fact]
    public async Task EmbedAsync_reflects_the_input_text_not_just_the_CLS_token()
    {
        // The fixture's mean-pooling graph (see its header comment) makes the output depend on
        // every real token, not just position 0 — so different inputs must not collapse to
        // the same vector the way a naive CLS-only passthrough over an un-contextualized
        // Gather would.
        var v1 = await _embedder.EmbedAsync("cat sat on the mat", TestContext.Current.CancellationToken);
        var v2 = await _embedder.EmbedAsync("quarterly revenue grew", TestContext.Current.CancellationToken);

        Assert.NotEqual(v1.ToArray(), v2.ToArray());
    }

    [Fact]
    public async Task EmbedBatchAsync_preserves_input_order()
    {
        string[] texts = ["hello world", "cat sat", "dog running", "quarterly revenue grew by percent"];

        var batch = await _embedder.EmbedBatchAsync(texts, TestContext.Current.CancellationToken);

        Assert.Equal(texts.Length, batch.Count);
        for (var i = 0; i < texts.Length; i++)
        {
            var single = await _embedder.EmbedAsync(texts[i], TestContext.Current.CancellationToken);
            Assert.Equal(single.ToArray(), batch[i].ToArray());
        }
    }

    [Fact]
    public async Task EmbedBatchAsync_of_empty_input_returns_empty()
    {
        var batch = await _embedder.EmbedBatchAsync([], TestContext.Current.CancellationToken);
        Assert.Empty(batch);
    }
}
