using System.Text;
using Netclaw.Configuration;

namespace Netclaw.Actors.Skills;

/// <summary>
/// Mutable registry holding discovered <see cref="SkillEntry"/> items.
/// Follows the same pattern as <see cref="Tools.ToolRegistry"/>.
/// </summary>
public sealed class SkillRegistry
{
    private readonly List<SkillEntry> _skills = new();

    /// <summary>
    /// Trigger phrases generated by the enrichment service, keyed by skill name.
    /// Used in the compressed index. Thread-safe via volatile dictionary swap.
    /// </summary>
    private volatile IReadOnlyDictionary<string, string> _triggerPhrases =
        new Dictionary<string, string>();

    /// <summary>
    /// Pre-built compressed menus per audience. Rebuilt after registration
    /// changes or enrichment updates.
    /// </summary>
    private volatile IReadOnlyDictionary<TrustAudience, string> _audienceMenus =
        new Dictionary<TrustAudience, string>();

    /// <summary>
    /// Slash-command dispatch map: skill name → entry, for skills where
    /// <see cref="SkillEntry.UserInvocable"/> is true.
    /// </summary>
    private readonly Dictionary<string, SkillEntry> _slashCommands = new(StringComparer.OrdinalIgnoreCase);

    public void Register(SkillEntry skill)
    {
        _skills.Add(skill);
        if (skill.UserInvocable)
            _slashCommands[skill.Name] = skill;
    }

    /// <summary>
    /// Remove all registered skills so the registry can be re-populated
    /// (e.g. after a feed sync updates on-disk skill files).
    /// </summary>
    public void Clear()
    {
        _skills.Clear();
        _slashCommands.Clear();
        _audienceMenus = new Dictionary<TrustAudience, string>();
    }

    public IReadOnlyList<SkillEntry> GetAll() => _skills;

    /// <summary>
    /// Case-insensitive substring search against name, display name, and description.
    /// </summary>
    public IReadOnlyList<SkillEntry> Search(string query, int maxResults = 5)
    {
        if (string.IsNullOrWhiteSpace(query))
            return [];

        var queryLower = query.Trim().ToLowerInvariant();

        return _skills
            .Where(s =>
                s.Name.Contains(queryLower, StringComparison.OrdinalIgnoreCase)
                || s.DisplayName.Contains(queryLower, StringComparison.OrdinalIgnoreCase)
                || s.Description.Contains(queryLower, StringComparison.OrdinalIgnoreCase))
            .Take(maxResults)
            .ToList();
    }

    /// <summary>
    /// Replace the enrichment-generated trigger phrases and rebuild per-audience menus.
    /// Called by <c>SkillIndexEnrichmentService</c> after enrichment completes.
    /// </summary>
    public void SetTriggerPhrases(IReadOnlyDictionary<string, string> phrases)
    {
        _triggerPhrases = phrases;
        RebuildAudienceMenus();
    }

    /// <summary>
    /// Returns the pre-built compressed menu for the given audience.
    /// Returns empty string if no menu has been built yet.
    /// </summary>
    public string GetMenuForAudience(TrustAudience audience)
    {
        return _audienceMenus.TryGetValue(audience, out var menu) ? menu : string.Empty;
    }

    /// <summary>
    /// Rebuild pre-built menus for all audience levels.
    /// Call after registration changes, enrichment updates, or re-scan.
    /// </summary>
    public void RebuildAudienceMenus()
    {
        var menus = new Dictionary<TrustAudience, string>();
        foreach (var audience in Enum.GetValues<TrustAudience>())
        {
            menus[audience] = GenerateCompressedMenu(audience);
        }
        _audienceMenus = menus;
    }

    /// <summary>
    /// Backwards-compatible overload. Returns the Personal audience menu
    /// (most permissive — all skills visible).
    /// </summary>
    public string GenerateDescriptionMenu()
    {
        // If pre-built menus exist, use them
        if (_audienceMenus.TryGetValue(TrustAudience.Personal, out var menu)
            && !string.IsNullOrEmpty(menu))
        {
            return menu;
        }

        // Fallback: generate on the fly (first call before menus are built)
        return GenerateCompressedMenu(TrustAudience.Personal);
    }

    /// <summary>
    /// Generates a compressed pipe-delimited skill index for the given audience.
    /// Skills are filtered by trust tier visibility and tool availability.
    /// Skills with <c>DisableModelInvocation</c> are excluded.
    /// </summary>
    internal string GenerateCompressedMenu(TrustAudience audience)
    {
        if (_skills.Count == 0)
            return string.Empty;

        var visible = _skills
            .Where(s => IsVisibleForAudience(s, audience))
            .ToList();

        if (visible.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("[skills]|load via skill_load(name)|invoke via /name");

        // Group by category, null category = root
        var groups = visible
            .GroupBy(s => s.Category ?? "user")
            .OrderBy(g => g.Key);

        foreach (var group in groups)
        {
            foreach (var skill in group)
            {
                var phrase = GetTriggerPhrase(skill);
                sb.AppendLine($"|{group.Key}:{{{skill.Name}}} — {phrase}");
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Determines whether a skill should appear in the compressed index
    /// for the given audience.
    /// </summary>
    private static bool IsVisibleForAudience(SkillEntry skill, TrustAudience audience)
    {
        // Skills with disable-model-invocation are excluded from the LLM index
        // (they remain invokable via slash commands)
        if (skill.DisableModelInvocation)
            return false;

        // Trust tier visibility: skill's minimum audience must be <= session audience
        var minAudience = skill.TrustTier.DefaultMinimumAudience();
        if (audience < minAudience)
            return false;

        return true;
    }

    /// <summary>
    /// Returns the trigger phrase for a skill: enrichment-generated if available,
    /// otherwise truncated description as fallback.
    /// </summary>
    private string GetTriggerPhrase(SkillEntry skill)
    {
        if (_triggerPhrases.TryGetValue(skill.Name, out var phrase)
            && !string.IsNullOrWhiteSpace(phrase))
        {
            return phrase;
        }

        // Fallback: first 60 chars of description
        var desc = skill.Description;
        return desc.Length <= 60 ? desc : desc[..57] + "...";
    }

    // --- Slash-command dispatch ---

    /// <summary>
    /// Attempts to resolve a slash command from user input.
    /// Returns true if the input starts with / and matches a registered skill name.
    /// </summary>
    public bool TryResolveSlashCommand(string input, out SkillEntry? skill, out string remainder)
    {
        skill = null;
        remainder = string.Empty;

        if (string.IsNullOrWhiteSpace(input) || input[0] != '/')
            return false;

        var trimmed = input[1..]; // strip leading /
        var spaceIndex = trimmed.IndexOf(' ', StringComparison.Ordinal);
        var commandName = spaceIndex >= 0 ? trimmed[..spaceIndex] : trimmed;
        remainder = spaceIndex >= 0 ? trimmed[(spaceIndex + 1)..].Trim() : string.Empty;

        return _slashCommands.TryGetValue(commandName, out skill);
    }

    /// <summary>
    /// Returns all registered slash commands for error message generation.
    /// </summary>
    public IReadOnlyList<(string Command, string? ArgumentHint)> GetAvailableSlashCommands()
    {
        return _slashCommands.Values
            .OrderBy(s => s.Name)
            .Select(s => ($"/{s.Name}", s.ArgumentHint))
            .ToList();
    }
}
