// -----------------------------------------------------------------------
// <copyright file="MattermostCallbackActionStore.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using System.Collections.Concurrent;
using System.Security.Cryptography;

namespace Netclaw.Channels.Mattermost;

/// <summary>
/// Stores one-time opaque callback actions for Mattermost interactive approvals.
/// The token is generated by the daemon, embedded in the button context, and
/// consumed exactly once when the callback returns.
/// </summary>
public sealed class MattermostCallbackActionStore(TimeProvider timeProvider)
{
    /// <summary>
    /// Hard upper bound on outstanding callback actions. Each approval prompt
    /// mints one token per button (typically 5 buttons per prompt), so this
    /// caps the dictionary at roughly 2000 concurrent unanswered prompts. The
    /// cap defends against memory pressure from unclicked tokens — for example
    /// a session that triggers many approvals and never answers them, or a
    /// burst of approvals that aborts before user interaction. Oldest entries
    /// are evicted first.
    /// </summary>
    internal const int MaxEntries = 10_000;

    private static readonly TimeSpan EntryLifetime = TimeSpan.FromHours(12);
    private static readonly TimeSpan CleanupInterval = TimeSpan.FromMinutes(15);

    private readonly ConcurrentDictionary<string, StoredAction> _entries = new(StringComparer.Ordinal);
    private readonly ConcurrentQueue<string> _insertionOrder = new();
    private readonly Lock _cleanupLock = new();
    private DateTimeOffset _nextCleanupAt = timeProvider.GetUtcNow().Add(CleanupInterval);

    public string CreateAction(
        string channelId,
        string callId,
        string selectedKey,
        string rootPostId,
        string? requesterSenderId)
    {
        var token = CreateToken();
        var now = timeProvider.GetUtcNow();
        var entry = new StoredAction(
            ChannelId: channelId,
            CallId: callId,
            SelectedKey: selectedKey,
            RootPostId: rootPostId,
            RequesterSenderId: requesterSenderId,
            ExpiresAt: now.Add(EntryLifetime));

        _entries[token] = entry;
        _insertionOrder.Enqueue(token);
        EvictExcess();
        CleanupExpired(now);
        return token;
    }

    /// <summary>
    /// Records the actual prompt post ID against every outstanding token for the
    /// given <paramref name="callId"/>. Called by the session binding actor after
    /// <c>PostReplyAsync</c> returns, so the callback endpoint can verify that
    /// any <c>payload.PostId</c> supplied by the client matches the prompt this
    /// token was minted for — closing the forgery vector tracked under #939's
    /// review (a token-holder rewriting <c>post_id</c> to target an unrelated
    /// post the bot has edit permissions for).
    /// </summary>
    public void AssociatePromptPostId(string callId, string promptPostId)
    {
        if (string.IsNullOrWhiteSpace(callId) || string.IsNullOrWhiteSpace(promptPostId))
            return;

        foreach (var pair in _entries)
        {
            if (!string.Equals(pair.Value.CallId, callId, StringComparison.Ordinal))
                continue;
            if (pair.Value.PromptPostId is not null)
                continue;

            // ConcurrentDictionary.TryUpdate guards against concurrent eviction /
            // consume; if the entry has been removed or already updated, skip.
            var updated = pair.Value with { PromptPostId = promptPostId };
            _entries.TryUpdate(pair.Key, updated, pair.Value);
        }
    }

    /// <summary>
    /// Current count of outstanding (unconsumed, unexpired) actions. Exposed
    /// for diagnostics and tests; not used by the consume path.
    /// </summary>
    internal int Count => _entries.Count;

    public bool TryConsume(string token, out StoredAction? action)
    {
        action = null;
        var now = timeProvider.GetUtcNow();
        CleanupExpired(now);

        if (!_entries.TryRemove(token, out var entry))
            return false;

        if (entry.ExpiresAt < now)
            return false;

        action = entry;
        return true;
    }

    public sealed record StoredAction(
        string ChannelId,
        string CallId,
        string SelectedKey,
        string RootPostId,
        string? RequesterSenderId,
        DateTimeOffset ExpiresAt)
    {
        /// <summary>
        /// The actual Mattermost post ID of the prompt that carries this token's
        /// button. Populated by <see cref="MattermostCallbackActionStore.AssociatePromptPostId"/>
        /// after the binding actor's <c>PostReplyAsync</c> returns. The callback
        /// endpoint validates <c>payload.PostId</c> against this value — any
        /// mismatch is a forgery attempt (the token holder rewrote <c>post_id</c>
        /// to target an unrelated post). See issue #939.
        /// </summary>
        public string? PromptPostId { get; init; }
    }

    private static string CreateToken()
    {
        Span<byte> bytes = stackalloc byte[32];
        RandomNumberGenerator.Fill(bytes);
        return Convert.ToHexString(bytes).ToLowerInvariant();
    }

    /// <summary>
    /// Drops the oldest entries until <see cref="_entries"/> is at or under
    /// <see cref="MaxEntries"/>. The insertion-order queue may contain
    /// tombstones (tokens already consumed by <see cref="TryConsume"/>), which
    /// are skipped implicitly — <c>TryRemove</c> is a no-op on a missing key.
    /// </summary>
    private void EvictExcess()
    {
        while (_entries.Count > MaxEntries
               && _insertionOrder.TryDequeue(out var oldest))
        {
            _entries.TryRemove(oldest, out _);
        }
    }

    private void CleanupExpired(DateTimeOffset now)
    {
        if (now < _nextCleanupAt)
            return;

        lock (_cleanupLock)
        {
            if (now < _nextCleanupAt)
                return;

            foreach (var pair in _entries)
            {
                if (pair.Value.ExpiresAt < now)
                    _entries.TryRemove(pair.Key, out _);
            }

            _nextCleanupAt = now.Add(CleanupInterval);
        }
    }
}
